import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import type { Metadata } from 'next'
import { Inter as FontSans, Montserrat } from 'next/font/google'
import { cookies } from 'next/headers'
import RecoilProvider from './atoms/RecoilProvider'
import Login from './auth/_components/Login'
import './globals.css'
import SupabaseProvider from './supabase/supabase-provider'
import Navbar from './_components/Navbar'
import { cn } from './_utils'

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
})
const mont = Montserrat({
  subsets: ['latin'],
  variable: '--font-Montserrat',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const supabase = createServerComponentClient({ cookies })
  const {
    data: { session },
  } = await supabase.auth.getSession()

  return (
    <SupabaseProvider>
      <RecoilProvider>
        <html lang='en'>
          <body
            className={cn(
              'bg-slate-50 font-sans antialiased overflow-x-hidden',
              fontSans.variable,
              mont.variable
            )}>
            <main className='min-h-screen w-full flex-1 relative max-w-5xl mx-auto'>
              {session?.user ? (
                <>
                  <Navbar />
                  {children}
                </>
              ) : (
                <Login />
              )}
            </main>
          </body>
        </html>
      </RecoilProvider>
    </SupabaseProvider>
  )
}
